### ISSUE TITLE
bundler not installed

### ISSUE THREAD

**Issue by raysuelzer** [MushroomObserver/developer-startup#12]
Tried building the VM twice and ran into the same problem.  When it gets time to "bundle install" anything it fails because bundler isn't installed on the VM.  The solution I have found is to run `sudo apt-get install bundler` on the VM before running mo-dev \dir

Has anyone else had this problem?  If so, we should probably just add it as the first line in the bash script.

**Comment by pellaea** [comment]
Yes, many of us have had that problem at various points.  I always forget
what the solution is.  I think in one case I just didn't notice the little
message about sourcing /home/vagrant/.rvm/scripts/rvm.  The reason we don't
add "apt-get install bundler" is that this particular error message is just
a symptom of something deeper, and we keep (eventually) finding and fixing
that problem instead.

-Jason

**Comment by raysuelzer** [comment]
hah.  Yes.  The problem is that it starts to try and install things before
that rvm line is run...

Ray Suelzer
Mobile: (312) 869-2665

**Comment by JoeCohen** [comment]
This appears to have been fixed.
